export const DECK = [
  ["actually", "en realidad (≠ actualmente = currently)", "Actually, I prefer tea.", "falso amigo"],
  ["embarrassed", "avergonzado (≠ embarazada = pregnant)", "I was so embarrassed when I fell.", "falso amigo"],
  ["realize", "darse cuenta (≠ realizar = carry out)", "I didn't realize it was so late.", "falso amigo"],
  ["career", "trayectoria profesional (≠ carrera = degree)", "She has had a long career in finance.", "falso amigo"],
  ["attend", "asistir a (≠ atender = serve)", "I attended the meeting online.", "falso amigo"],
  ["library", "biblioteca (≠ librería = bookstore)", "I study at the library on Saturdays.", "falso amigo"],
  ["sensible", "sensato (≠ sensible = sensitive)", "That's a sensible decision.", "falso amigo"],
  ["success", "éxito (≠ exit = salida)", "The launch was a huge success.", "falso amigo"],
  ["eventually", "finalmente, con el tiempo (≠ eventualmente)", "Eventually, we found a solution.", "falso amigo"],
  ["support", "apoyar (≠ soportar = put up with)", "My family always supports me.", "falso amigo"],
  ["argument", "discusión, pelea (≠ argumento = plot)", "They had an argument about money.", "falso amigo"],
  ["have a cold", "estar resfriado (≠ constipated = estreñido)", "I can't come, I have a cold.", "falso amigo"],
  ["figure out", "descifrar, entender", "I finally figured out the problem.", "phrasal verb"],
  ["look forward to", "esperar con ganas", "I look forward to hearing from you.", "phrasal verb"],
  ["put off", "posponer", "Don't put off the meeting again.", "phrasal verb"],
  ["run out of", "quedarse sin", "We ran out of coffee.", "phrasal verb"],
  ["come up with", "idear, proponer", "She came up with a great idea.", "phrasal verb"],
  ["get along with", "llevarse bien con", "I get along with my coworkers.", "phrasal verb"],
  ["follow up", "dar seguimiento", "I'll follow up with an email.", "phrasal verb"],
  ["set up", "configurar, organizar", "Can you set up the meeting?", "phrasal verb"],
  ["turn down", "rechazar", "He turned down the job offer.", "phrasal verb"],
  ["catch up", "ponerse al día", "Let's catch up over lunch.", "phrasal verb"],
  ["make a decision", "tomar una decisión (no «take»)", "We need to make a decision today.", "colocación"],
  ["meet a deadline", "cumplir un plazo", "We met the deadline just in time.", "colocación"],
  ["take a break", "tomar un descanso", "Let's take a ten-minute break.", "colocación"],
  ["give a presentation", "hacer una presentación", "I'm giving a presentation tomorrow.", "colocación"],
  ["ask a question", "hacer una pregunta (no «make»)", "Can I ask you a question?", "colocación"],
  ["reach an agreement", "llegar a un acuerdo", "We reached an agreement after hours.", "colocación"],
  ["pay attention", "prestar atención", "Please pay attention to the details.", "colocación"],
  ["do business", "hacer negocios", "We've done business with them for years.", "colocación"],
];
