/* Frases para dictado por banda (A: A1–A2, B: B1–B2, C: C1–C2). */
export const DICTATION = {
  A: [
    "I usually get up at seven o'clock.",
    "My sister works in a big hospital.",
    "Can you help me with my homework?",
    "We had pizza for dinner last night.",
    "The bus stop is next to the bank.",
    "I don't like coffee without sugar.",
    "There are three bedrooms in my house.",
    "She is going to visit her parents on Sunday.",
    "How much does this jacket cost?",
    "It was very cold in the morning.",
    "They live near the beach in Lima.",
    "I'm learning English for my new job.",
  ],
  B: [
    "I've been working on this report since Monday.",
    "If I had more time, I would travel around the world.",
    "The meeting was postponed because the manager was sick.",
    "She suggested taking the train instead of driving.",
    "We need to figure out how to reduce our expenses.",
    "Have you ever thought about starting your own business?",
    "The results will be announced at the end of the month.",
    "I'm looking forward to hearing from you soon.",
    "Although it was raining, we decided to go for a walk.",
    "He apologized for not replying to my email earlier.",
    "Could you let me know when the documents are ready?",
    "The new policy has been criticized by many employees.",
  ],
  C: [
    "Had we known about the delay, we would have rescheduled the call.",
    "The findings are consistent with what previous studies have suggested.",
    "Not only did she meet the deadline, but she also exceeded expectations.",
    "It is widely believed that remote work has boosted productivity.",
    "The proposal, which was submitted last week, is still under review.",
    "Hardly had the presentation started when the projector broke down.",
    "Whether or not the merger goes ahead depends on the regulators.",
    "The company is said to be considering a significant restructuring.",
    "Rarely do we see such a dramatic shift in consumer behaviour.",
    "Despite the setbacks, the team managed to deliver on time.",
    "Were the tax rules to change, our forecasts would need revising.",
    "She would rather we discussed the matter in person.",
  ],
};
