export const GRAMMAR = [
  { id: "pres", lv: "A1", name: "Present simple vs continuous",
    exp: "Presente simple: hábitos, rutinas y verdades generales (I work every day). Presente continuo: lo que pasa ahora o es temporal (I'm working on a project this month). Los verbos de estado (know, like, want, need, believe) casi nunca van en continuo.",
    formula: "I work / she works   ·   I am working / she is working",
    ex: ["She works in a bank.", "Right now she is talking to a client.", "I know the answer (not: I'm knowing)."],
    qs: [
      { s: "She ___ to work every day.", o: ["goes", "is going", "go"], a: 0, why: "«Every day» indica rutina → presente simple, y la 3.ª persona lleva -s." },
      { s: "Look! It ___ .", o: ["rains", "is raining", "rain"], a: 1, why: "«Look!» señala algo que pasa en este momento → continuo." },
      { s: "I ___ what you mean.", o: ["know", "am knowing"], a: 0, why: "«Know» es verbo de estado: no se usa en continuo." },
      { s: "This month we ___ on a new project.", o: ["work", "are working"], a: 1, why: "Es una situación temporal → continuo." },
    ] },
  { id: "past", lv: "A2", name: "Past simple",
    exp: "Acciones terminadas en un momento definido (yesterday, last week, in 2020). Verbos regulares + ed; los irregulares se memorizan (go → went). En negativas y preguntas usa did + verbo base: I didn't go · Did you go?",
    formula: "I worked / I went   ·   I didn't go   ·   Did you go?",
    ex: ["Yesterday I went to the bank.", "We didn't like the movie.", "Did you call her?"],
    qs: [
      { s: "Yesterday I ___ to the bank.", o: ["go", "went", "gone"], a: 1, why: "Pasado terminado con «yesterday» → past simple. «Go» es irregular: went." },
      { s: "We didn't ___ the movie.", o: ["like", "liked"], a: 0, why: "Después de didn't va el verbo base, sin -ed." },
      { s: "___ you call her last night?", o: ["Do", "Did", "Were"], a: 1, why: "Pregunta en pasado con verbo normal → Did + verbo base." },
      { s: "She ___ me a great idea.", o: ["gave", "gived", "give"], a: 0, why: "«Give» es irregular: give → gave → given." },
    ] },
  { id: "comp", lv: "A2", name: "Comparativos y superlativos",
    exp: "Adjetivos cortos: + er / the + est (cheap → cheaper → the cheapest). Largos: more / the most (more expensive). Irregulares: good → better → the best; bad → worse → the worst. Nunca «more better».",
    formula: "cheaper than · the cheapest   ·   more useful than · the most useful",
    ex: ["My new phone is faster than the old one.", "This is the best restaurant in town.", "English is easier than I thought."],
    qs: [
      { s: "My new phone is ___ than the old one.", o: ["more fast", "faster", "fastest"], a: 1, why: "«Fast» es corto → faster than." },
      { s: "This is ___ restaurant in town.", o: ["the best", "the better", "the most good"], a: 0, why: "Superlativo irregular de good: the best." },
      { s: "English is ___ than I thought.", o: ["more easy", "easier"], a: 1, why: "Adjetivos terminados en -y: easy → easier." },
      { s: "The second option is ___ .", o: ["more expensive", "expensiver"], a: 0, why: "Adjetivo largo (3 sílabas) → more expensive." },
    ] },
  { id: "fut", lv: "A2", name: "Will vs going to",
    exp: "Going to: planes ya decididos y predicciones con evidencia (Look at those clouds — it's going to rain). Will: decisiones en el momento, promesas, ofertas y predicciones de opinión (I think you'll like it).",
    formula: "I'm going to + verbo (plan)   ·   I'll + verbo (decisión ahora)",
    ex: ["I've booked the hotel: we're going to visit Cusco.", "The phone is ringing. I'll get it!", "I promise I won't be late."],
    qs: [
      { s: "I've bought the tickets. We ___ visit London.", o: ["will", "are going to"], a: 1, why: "Plan ya decidido (compraste los boletos) → going to." },
      { s: "The phone is ringing. — I ___ answer it!", o: ["'ll", "am going to"], a: 0, why: "Decisión espontánea en el momento → will." },
      { s: "I promise I ___ tell anyone.", o: ["won't", "am not going to"], a: 0, why: "Las promesas usan will / won't." },
      { s: "Look at that car! It ___ crash!", o: ["will", "is going to"], a: 1, why: "Predicción con evidencia visible → going to." },
    ] },
  { id: "pp", lv: "B1", name: "Present perfect vs past simple",
    exp: "Present perfect (have + participio) conecta el pasado con el presente: experiencias sin fecha (I've visited Cusco), resultados actuales (I've lost my keys) y situaciones que continúan (I've lived here since 2020). Si dices CUÁNDO (yesterday, in 2019), usa past simple.",
    formula: "I have + participio (been, done, seen)   ·   + fecha → past simple",
    ex: ["I've been to Mexico three times.", "She finished the report yesterday.", "Have you ever eaten ceviche?"],
    qs: [
      { s: "I ___ to Mexico three times.", o: ["have been", "went", "was"], a: 0, why: "Experiencia de vida sin fecha → present perfect." },
      { s: "She ___ the report yesterday.", o: ["has finished", "finished"], a: 1, why: "«Yesterday» es un momento definido → past simple." },
      { s: "___ you ever ___ sushi?", o: ["Did / eat", "Have / eaten"], a: 1, why: "«Ever» pregunta por experiencias → Have you ever + participio." },
      { s: "We ___ here since 2020.", o: ["have lived", "lived", "live"], a: 0, why: "Situación que empezó en el pasado y sigue → present perfect + since." },
    ] },
  { id: "for", lv: "B1", name: "For vs since",
    exp: "For + duración (for three years, for a long time). Since + punto de inicio (since 2019, since Monday, since I was a child). Nunca «since three years». Suelen ir con present perfect.",
    formula: "for + cuánto tiempo   ·   since + desde cuándo",
    ex: ["I've worked here for five years.", "She's been sick since Tuesday.", "We've been friends since we were kids."],
    qs: [
      { s: "I've worked here ___ five years.", o: ["for", "since"], a: 0, why: "«Five years» es una duración → for." },
      { s: "She has been sick ___ Tuesday.", o: ["for", "since"], a: 1, why: "«Tuesday» es el punto de inicio → since." },
      { s: "We've known each other ___ we were kids.", o: ["for", "since"], a: 1, why: "Una frase que marca cuándo empezó → since." },
      { s: "They waited ___ two hours.", o: ["for", "since"], a: 0, why: "Duración → for." },
    ] },
  { id: "cond", lv: "B1", name: "Condicionales 1 y 2",
    exp: "1.er condicional (real o probable): If + presente, will + verbo (If it rains, I'll stay home). 2.º condicional (hipotético): If + pasado, would + verbo (If I had more time, I would travel). Con «to be» se prefiere «were»: If I were you…",
    formula: "If + present → will   ·   If + past → would",
    ex: ["If you study, you'll pass.", "If I were you, I'd accept the offer.", "She'll call you if she has time."],
    qs: [
      { s: "If you study, you ___ the exam.", o: ["will pass", "would pass", "pass"], a: 0, why: "Situación real o probable → 1.er condicional: will." },
      { s: "If I ___ rich, I would buy a house.", o: ["am", "were", "will be"], a: 1, why: "Hipótesis irreal → 2.º condicional con «were»." },
      { s: "If I were you, I ___ accept the offer.", o: ["will", "would"], a: 1, why: "«If I were you» es hipotético → would." },
      { s: "She will call you if she ___ time.", o: ["has", "will have"], a: 0, why: "Después de «if» no se usa will: presente simple." },
    ] },
  { id: "ger", lv: "B1", name: "Gerundio vs infinitivo",
    exp: "Algunos verbos van con -ing (enjoy, avoid, finish, mind, suggest, consider): I enjoy reading. Otros con to + verbo (want, decide, need, hope, plan, promise): I want to learn. Después de preposición siempre -ing: I'm interested in learning. Ojo: look forward to + -ing.",
    formula: "enjoy / avoid / finish + -ing   ·   want / decide / need + to",
    ex: ["I enjoy listening to podcasts.", "We decided to buy a new car.", "I'm looking forward to seeing you."],
    qs: [
      { s: "I enjoy ___ podcasts.", o: ["listening to", "to listen to"], a: 0, why: "«Enjoy» siempre va seguido de -ing." },
      { s: "We decided ___ a new car.", o: ["buying", "to buy"], a: 1, why: "«Decide» va con to + verbo." },
      { s: "I'm looking forward to ___ you.", o: ["see", "seeing"], a: 1, why: "En «look forward to», «to» es preposición → -ing." },
      { s: "She avoided ___ the question.", o: ["answering", "to answer"], a: 0, why: "«Avoid» va con -ing." },
    ] },
  { id: "pass", lv: "B2", name: "Voz pasiva",
    exp: "be + participio cuando importa la acción o el objeto, no quién la hace: The report was written by Ana. Presente: is made · pasado: was made · perfecto: has been made · futuro: will be made.",
    formula: "objeto + be (conjugado) + participio (+ by …)",
    ex: ["English is spoken all over the world.", "The bridge was built in 1990.", "Your order has been sent."],
    qs: [
      { s: "English ___ all over the world.", o: ["speaks", "is spoken", "is speaking"], a: 1, why: "El idioma no habla: es hablado → pasiva en presente." },
      { s: "The bridge ___ in 1990.", o: ["was built", "built", "is built"], a: 0, why: "Pasado con fecha → was + participio." },
      { s: "Your order has ___ sent.", o: ["been", "be", "being"], a: 0, why: "Pasiva en present perfect: has been + participio." },
      { s: "The results ___ tomorrow.", o: ["will announce", "will be announced"], a: 1, why: "Los resultados no anuncian: serán anunciados." },
    ] },
  { id: "cond3", lv: "B2", name: "Tercer condicional",
    exp: "Para imaginar un pasado diferente: If + had + participio, would have + participio. If I had studied, I would have passed. Sirve para arrepentimientos y para analizar errores.",
    formula: "If + had + participio → would have + participio",
    ex: ["If I had known, I would have told you.", "We would have won if we had trained harder."],
    qs: [
      { s: "If I had known, I ___ you.", o: ["would tell", "would have told", "told"], a: 1, why: "Pasado imaginario → would have + participio." },
      { s: "If she ___ earlier, she wouldn't have missed the bus.", o: ["left", "had left", "would leave"], a: 1, why: "En la parte del «if» va had + participio." },
      { s: "We would have won if we ___ harder.", o: ["had trained", "trained"], a: 0, why: "Condición en el pasado → had + participio." },
      { s: "If they had invited me, I ___ .", o: ["would have gone", "would go"], a: 0, why: "Resultado en el pasado → would have gone." },
    ] },
];
