export const SOUNDS = [
  { id: "th", name: "La TH", ipa: "/θ/ /ð/", tip: "Pon la punta de la lengua entre los dientes y sopla. No es «t» ni «d»: es un sonido nuevo para el español latino.",
    pairs: ["think · sink", "three · tree", "thank · tank", "they · day"],
    sents: ["I think three things are worth it.", "This is the thing that they wanted.", "Thank you for the thoughtful gift."] },
  { id: "ii", name: "Ship o sheep", ipa: "/ɪ/ /iː/", tip: "/ɪ/ es corta y relajada, entre «i» y «e» (ship). /iː/ es larga y tensa, como sonriendo (sheep). Si las igualas, «sheet» y «beach» suenan a otra cosa.",
    pairs: ["ship · sheep", "sit · seat", "live · leave", "fill · feel"],
    sents: ["Please sit in this seat.", "The ship carried sheep across the sea.", "Is it easy to leave early?"] },
  { id: "vb", name: "V y B", ipa: "/v/ /b/", tip: "/v/: dientes de arriba sobre el labio inferior y haz vibrar. /b/: labios juntos. En inglés son sonidos distintos: «very» ≠ «berry».",
    pairs: ["very · berry", "vote · boat", "van · ban", "vest · best"],
    sents: ["Very good, Victor, we have a van.", "Vote for the best video.", "I love living in a village."] },
  { id: "sc", name: "S inicial sin «e»", ipa: "/sp/ /st/ /sk/", tip: "No agregues una «e» al comienzo: «student», no «estudent»; «Spain», no «Espain». Empieza directo con un siseo.",
    pairs: ["speak", "student", "school", "street"],
    sents: ["Smart students start early.", "Stop speaking so fast in the street.", "She studies Spanish at school."] },
  { id: "ed", name: "Finales en -ed", ipa: "/t/ /d/ /ɪd/", tip: "-ed suena /t/ tras sonidos sordos (worked), /d/ tras sonoros (played) y /ɪd/ solo tras t o d (wanted). «Worked» tiene una sola sílaba.",
    pairs: ["worked /t/", "played /d/", "wanted /ɪd/", "asked /t/"],
    sents: ["I worked, played and waited.", "She asked and laughed.", "We needed it and started it."] },
  { id: "sh", name: "SH y CH", ipa: "/ʃ/ /tʃ/", tip: "/ʃ/ es un siseo continuo, como pidiendo silencio (she). /tʃ/ empieza con un pequeño golpe, como la «ch» española (cheap).",
    pairs: ["share · chair", "ship · chip", "wash · watch", "sheet · cheat"],
    sents: ["She chose a cheap shirt.", "Check the sheet, Charlie.", "The chef shares his chips."] },
  { id: "h", name: "La H suave", ipa: "/h/", tip: "La h inglesa es solo aire, como empañar un vidrio. No raspes la garganta como con la «j» española.",
    pairs: ["hat · at", "heart · art", "hold · old", "hair · air"],
    sents: ["How hard is it to help him?", "Happy hours at the hotel.", "He has a huge house on the hill."] },
  { id: "ae", name: "Cat o cut", ipa: "/æ/ /ʌ/", tip: "/æ/ abre mucho la boca, mezcla de «a» y «e» (cat). /ʌ/ es una «a» corta y relajada (cut).",
    pairs: ["cat · cut", "hat · hut", "bag · bug", "ran · run"],
    sents: ["The cat sat on my hat.", "I had bad luck with the bus.", "Run back and grab the cup."] },
];
