/* Las 30 voces prediseñadas de Gemini (sirven para la voz natural y para Gemini Live). */
export const VOICES = [
  { id: "Kore", es: "Firme", g: "f" },
  { id: "Aoede", es: "Fresca", g: "f" },
  { id: "Leda", es: "Juvenil", g: "f" },
  { id: "Sulafat", es: "Cálida", g: "f" },
  { id: "Achernar", es: "Suave", g: "f" },
  { id: "Despina", es: "Serena", g: "f" },
  { id: "Vindemiatrix", es: "Gentil", g: "f" },
  { id: "Autonoe", es: "Brillante", g: "f" },
  { id: "Callirrhoe", es: "Tranquila", g: "f" },
  { id: "Erinome", es: "Clara", g: "f" },
  { id: "Laomedeia", es: "Alegre", g: "f" },
  { id: "Pulcherrima", es: "Directa", g: "f" },
  { id: "Gacrux", es: "Madura", g: "f" },
  { id: "Zephyr", es: "Luminosa", g: "f" },
  { id: "Puck", es: "Animado", g: "m" },
  { id: "Charon", es: "Informativo", g: "m" },
  { id: "Fenrir", es: "Entusiasta", g: "m" },
  { id: "Orus", es: "Firme", g: "m" },
  { id: "Achird", es: "Amigable", g: "m" },
  { id: "Iapetus", es: "Claro", g: "m" },
  { id: "Umbriel", es: "Relajado", g: "m" },
  { id: "Algieba", es: "Suave", g: "m" },
  { id: "Enceladus", es: "Susurrante", g: "m" },
  { id: "Algenib", es: "Grave", g: "m" },
  { id: "Rasalgethi", es: "Explicativo", g: "m" },
  { id: "Alnilam", es: "Seguro", g: "m" },
  { id: "Schedar", es: "Equilibrado", g: "m" },
  { id: "Zubenelgenubi", es: "Casual", g: "m" },
  { id: "Sadachbia", es: "Vivaz", g: "m" },
  { id: "Sadaltager", es: "Experto", g: "m" },
];
export const VOICE_IDS = VOICES.map(v => v.id);
export const voiceLabel = id => { const v = VOICES.find(x => x.id === id); return v ? `${v.id} · ${v.es}` : id; };
